---
- name: install search engine
  remote_user: root
  hosts: search
  tasks:
  - name: ensure apt has https support
    apt:
      pkg: apt-transport-https
    register: result
    until: result.rc is undefined or result.rc != 100
    retries: 5
    delay: 10

  - name: add yacy gpg key
    apt_key:
      url: https://bintray.com/user/downloadSubjectPublicKey?username=bintray

  - name: add yacy repo
    apt_repository:
      repo: deb https://dl.bintray.com/luccioman/yacy_search_server {{ ansible_distribution_release }} main

  - name: install packages
    apt:
      pkg:
        - yacy
        - nginx
      update_cache: yes

  - name: configre nginx for yacy
    template:
      src: files/nginx/default.j2
      dest: /etc/nginx/sites-available/default
    notify: restart nginx

  - name: ensure services are running
    systemd:
      name: "{{ item }}"
      state: started
      enabled: yes
    with_items:
      - nginx
      - yacy

  - name: wait for yacy to be up
    wait_for:
      port: 8090

  post_tasks:
  - name: finished
    debug:
      msg: Open your browser http://{{ ansible_ssh_host }}

  handlers:
  - name: restart nginx
    service:
      name: nginx
      state: restarted
