---
- name: install search engine
  remote_user: root
  hosts: search
  tasks:
  - name: add yacy gpg key
    apt_key: url='http://debian.yacy.net/yacy_orbiter_key.asc'

  - name: add yacy repo
    apt_repository: repo='deb http://debian.yacy.net /'

  - name: install packages
    apt: pkg={{ item }}
    with_items:
      - openjdk-7-jre-headless
      - yacy
      - nginx

  - name: configre nginx for yacy
    template: src=files/nginx/default.j2 dest=/etc/nginx/sites-available/default
    notify: restart nginx

  - name: ensure services are running
    service: name={{ item }} state=started enabled=yes
    with_items:
      - nginx
      - yacy

  - name: wait for yacy to be up
    wait_for: port=8090

  post_tasks:
  - name: finished
    debug: msg='Open your browser http://{{ ansible_ssh_host }}'

  handlers:
  - name: restart nginx
    service: name=nginx state=restarted
